Repository woowa-techcamp-2020/bmart-5, pull requests merged in 2020-08, with the labels that each got.

#30 chore: 프론트엔드 CRA 프로젝트 생성(with TypeScript) #7
  .gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/logo.svg
  client/src/react-app-env.d.ts
  client/src/serviceWorker.ts
  client/src/setupTests.ts
  client/tsconfig.json
Labels: env, frontend

#17 docs: 데이터베이스 erd.png #16
  assets/erd.png
Labels: backend, documentation

#32 chore: 클라이언트 프로젝트 디렉토리 구조 설정#9
  client/src/App.css
  client/src/App.tsx
  client/src/components/Header/index.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/logo.svg
  client/src/pages/MainPage/index.tsx
Labels: frontend

#52 chore: 간소화된 atomic pattern을 적용한 컴포넌트 디렉토리 구조 설계 #11
  client/package-lock.json
  client/src/components/atoms/Sample/Sample.spec.tsx
  client/src/components/atoms/Sample/Sample.tsx
  client/src/components/atoms/Sample/index.tsx
  client/src/components/modules/Header/index.tsx
  client/src/components/modules/Sample/Sample.spec.tsx
  client/src/components/modules/Sample/Sample.tsx
  client/src/components/modules/Sample/index.tsx
  client/src/components/templates/Sample/Sample.spec.tsx
  client/src/components/templates/Sample/Sample.tsx
  client/src/components/templates/Sample/index.tsx
  client/src/pages/MainPage/index.tsx
  client/yarn.lock
  package-lock.json
  yarn.lock
Labels: env, frontend

#59 chore: craco 이용해서 절대경로 세팅#54
  client/craco.config.js
  client/package.json
  client/src/App.tsx
  client/src/pages/MainPage/index.tsx
  client/tsconfig.json
  client/tsconfig.paths.json
  client/yarn.lock
Labels: env, frontend

#58 Connect mysql#19
  server/package.json
  server/src/config/consts.ts
  server/src/config/express.ts
  server/src/controllers/index.ts
  server/src/main.ts
  server/src/models/category.ts
  server/src/models/index.ts
  server/src/models/product.ts
  server/src/models/sub-category.ts
  server/src/modules/database/connection.ts
  server/src/modules/database/database.ts
  server/src/modules/database/db-service.ts
  server/src/modules/database/index.ts
  server/src/routers/index.ts
  server/yarn.lock
  shared/.env.sample
Labels: backend, feature

#57 chore: react 컴포넌트 자동 생성 스크립트 작성 #56
  client/create_react_component.sh
Labels: env, frontend

#61 feat: Slidable container 구현#37
  client/src/assets/images/coke.jpeg
  client/src/components/atoms/Icon/Icon.tsx
  client/src/components/modules/ContainerHeader/ContainerHeader.tsx
  client/src/components/modules/ContainerHeader/index.tsx
  client/src/components/modules/ContainerHeader/styled.tsx
  client/src/components/modules/ProductCard/ProductCard.tsx
  client/src/components/modules/ProductCard/index.tsx
  client/src/components/modules/ProductCard/styled.tsx
  client/src/components/modules/SlidableContainer/SlidableContainer.tsx
  client/src/components/modules/SlidableContainer/index.tsx
  client/src/components/modules/SlidableContainer/styled.tsx
  client/src/pages/MainPage/MainPage.tsx
  client/src/utils/constants.tsx
Labels: feature, frontend

#62 feat: ProductDetailInfo 컴포넌트 구현 #42
  client/src/App.tsx
  client/src/components/modules/ProductDetailInfo/ProductDetailInfo.spec.tsx
  client/src/components/modules/ProductDetailInfo/ProductDetailInfo.tsx
  client/src/components/modules/ProductDetailInfo/index.tsx
  client/src/components/modules/ProductDetailInfo/styled.tsx
  client/src/pages/ProductPage/ProductPage.spec.tsx
  client/src/pages/ProductPage/ProductPage.tsx
  client/src/pages/ProductPage/index.tsx
  client/src/utils/constants.tsx
Labels: feature, frontend

#63 Milestone1 apis#60
  .gitignore
  server/package.json
  server/src/config/constants.ts
  server/src/config/express.ts
  server/src/config/logger.ts
  server/src/controllers/category-controller.ts
  server/src/controllers/index.ts
  server/src/controllers/product-controller.ts
  server/src/controllers/sub-category-controller.ts
  server/src/main.ts
  server/src/modules/auth/passport.ts
  server/src/modules/database/connection.ts
  server/src/modules/database/db-service.ts
  server/src/modules/exception/custom-error.ts
  server/src/modules/exception/error-handler.ts
  server/src/routers/category-router.ts
  server/src/routers/index.ts
  server/src/routers/product-router.ts
  server/src/routers/sub-category-router.ts
  server/tsconfig.json
  server/yarn.lock
  tsconfig.json
Labels: backend, feature

#65 feat: Header 컴포넌트 재사용성 개선 #64
  client/src/components/atoms/Icon/Icon.tsx
  client/src/components/modules/Header/Header.tsx
  client/src/components/modules/Header/styled.tsx
  client/src/pages/MainPage/MainPage.tsx
  client/src/utils/constants.tsx
Labels: enhancement, feature, frontend

#68 chore: logo svg로 변경 #67
  client/src/components/atoms/Logo/Logo.tsx
  client/src/components/atoms/Logo/images/logo.png
  client/src/components/atoms/Logo/images/logo.svg
Labels: design, frontend, style

#66 feat: 배너 만들기 #35
  client/src/components/modules/Banner/Banner.spec.tsx
  client/src/components/modules/Banner/Banner.tsx
  client/src/components/modules/Banner/index.tsx
  client/src/components/modules/Banner/styled.tsx
  client/src/pages/MainPage/MainPage.tsx
  client/tsconfig.paths.json
Labels: feature, frontend

#74 docs: Update README.md
  README.md
Labels: design, documentation

#72 Fetch product#70
  client/package.json
  client/src/components/modules/ListLoading/ListLoading.tsx
  client/src/components/modules/ListLoading/index.tsx
  client/src/components/modules/ListLoading/styled.tsx
  client/src/components/modules/ProductCard/ProductCard.tsx
  client/src/components/modules/SlidableContainer/SlidableContainer.tsx
  client/src/utils/API.tsx
  client/src/utils/constants.tsx
  client/tsconfig.paths.json
  client/yarn.lock
  shared/dto/index.ts
  shared/dto/product-dto.ts
Labels: feature, frontend

#77 Category container#36
  client/scripts/bulk_create_category.sh
  client/scripts/create_react_component.sh
  client/src/assets/images/main-bread.png
  client/src/assets/images/main-choco.png
  client/src/assets/images/main-egg.png
  client/src/assets/images/main-hair.png
  client/src/assets/images/main-ice.png
  client/src/assets/images/main-mealkit.png
  client/src/assets/images/main-milk.png
  client/src/assets/images/main-salad.png
  client/src/assets/images/main-yasik.png
  client/src/assets/images/more.png
  client/src/components/modules/CategoryContainer/CategoryContainer.tsx
  client/src/components/modules/CategoryContainer/index.tsx
  client/src/components/modules/CategoryContainer/styled.tsx
  client/src/components/modules/CategoryIcon/CategoryIcon.tsx
  client/src/components/modules/CategoryIcon/index.tsx
  client/src/components/modules/CategoryIcon/styled.tsx
  client/src/components/modules/ContainerHeader/styled.tsx
  client/src/pages/MainPage/MainPage.tsx
  client/src/utils/constants.tsx
  server/src/controllers/category-controller.ts
  server/src/routers/category-router.ts
  server/src/routers/product-router.ts
  server/src/routers/sub-category-router.ts
Labels: backend, feature, frontend, script

#78 feat: github action 자동배포 스크립트 작성 #20
  .github/workflows/main.yml
  appspec.yml
Labels: deployment, env

#81 chore: Next.js 기반으로 클라이언트 이전#76
  .gitignore
  client/.babelrc
  client/craco.config.js
  client/next-env.d.ts
  client/next.config.js
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/components/modules/Banner/Banner.spec.tsx
  client/src/components/modules/Banner/Banner.tsx
  client/src/components/modules/Banner/index.ts
  client/src/components/modules/Banner/styled.ts
  client/src/components/modules/Banner/styled.tsx
  client/src/components/modules/Footer/Footer.tsx
  client/src/components/modules/Footer/index.ts
  client/src/components/modules/Footer/styled.ts
  client/src/components/templates/Layout/Layout.tsx
  client/src/components/templates/Layout/index.ts
  client/src/components/templates/Sample/Sample.spec.tsx
  client/src/components/templates/Sample/Sample.tsx
  client/src/components/templates/Sample/index.tsx
  client/src/index.tsx
  client/src/interfaces/index.ts
  client/src/pages/MainPage/MainPage.spec.tsx
  client/src/pages/MainPage/MainPage.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/ProductPage/ProductPage.spec.tsx
  client/src/pages/ProductPage/ProductPage.tsx
  client/src/pages/ProductPage/index.tsx
  client/src/pages/_docuement.tsx
  client/src/pages/about/index.tsx
  client/src/pages/index.tsx
  client/src/pages/temp/index.tsx
  client/src/react-app-env.d.ts
  client/src/serviceWorker.ts
  client/src/setupTests.ts
  client/src/utils/helper.tsx
  client/tsconfig.json
  client/tsconfig.paths.json
  client/yarn.lock
Labels: env, frontend

#82 Fetch mock data#12
  client/scripts/bulk_create_all.sh
  client/scripts/bulk_create_category.sh
  client/scripts/bulk_create_product.sh
  client/scripts/bulk_create_sub_category.sh
  client/scripts/data/fruits.txt
  client/scripts/data/vegetables.txt
  server/src/config/constants.ts
  server/src/config/express.ts
  server/src/controllers/product-controller.ts
  server/src/controllers/sub-category-controller.ts
  server/src/models/category.ts
  server/src/models/product.ts
  server/src/models/sub-category.ts
  server/src/routers/product-router.ts
  server/src/routers/sub-category-router.ts
Labels: backend, feature, frontend, script

#85 feat: github actions 자동 배포 스크립트 작성 #20
  .github/workflows/main.yml
  .gitignore
  appspec.yml
  client/package.json
  deploy.sh
Labels: deployment, env

#84 refactor : Next.js fetch 설정
  .gitignore
  client/src/components/modules/CategoryContainer/CategoryContainer.tsx
  client/src/components/modules/CategoryContainer/index.tsx
  client/src/components/modules/SlidableContainer/SlidableContainer.tsx
  client/src/components/modules/SlidableContainer/index.tsx
  client/src/pages/index.tsx
  client/src/pages/temp/index.tsx
  client/tsconfig.json
Labels: feature, frontend

#90 chore: 배포 브랜치 develop으로 변경 #89
  .github/workflows/main.yml
Labels: deployment, env

#94 fix: 이미지를 가져오지 못하는 버그 수정 #93
  client/scripts/data/fruits.txt
  client/scripts/data/vegetables.txt
  client/src/assets/images/index.tsx
  client/src/components/modules/CategoryContainer/CategoryContainer.tsx
  client/src/components/modules/ListLoading/ListLoading.tsx
  client/src/components/modules/SlidableContainer/SlidableContainer.tsx
  client/src/pages/index.tsx
  client/src/utils/helper.tsx
Labels: backend, bug, frontend

#92 fix: client 디렉토리에서 build 하도록 수정 #91
  .github/workflows/main.yml
Labels: env

#98 fix: create_react_component 경로 오류 수정 #97
  client/scripts/create_react_component.sh
Labels: bug

#101 feat: TabViewContainer 컴포넌트 구현 #69
  client/src/components/atoms/Badge/Badge.tsx
  client/src/components/atoms/Badge/index.tsx
  client/src/components/atoms/Badge/styled.tsx
  client/src/components/atoms/Icon/Icon.tsx
  client/src/components/atoms/SubButton/SubButton.tsx
  client/src/components/atoms/SubButton/index.tsx
  client/src/components/atoms/SubButton/styled.tsx
  client/src/components/modules/ContainerHeader/ContainerHeader.tsx
  client/src/components/modules/ContainerHeader/styled.tsx
  client/src/components/modules/ProductCard/ProductCard.tsx
  client/src/components/modules/ProductCard/styled.tsx
  client/src/components/modules/SlidableContainer/styled.tsx
  client/src/components/templates/CategoryContainer/CategoryContainer.tsx
  client/src/components/templates/CategoryContainer/index.tsx
  client/src/components/templates/CategoryContainer/styled.tsx
  client/src/components/templates/SlidableContainer/SlidableContainer.tsx
  client/src/components/templates/SlidableContainer/index.tsx
  client/src/components/templates/SlidableContainer/styled.tsx
  client/src/components/templates/TabViewContainer/TabViewContainer.tsx
  client/src/components/templates/TabViewContainer/index.tsx
  client/src/components/templates/TabViewContainer/styled.tsx
  client/src/pages/index.tsx
  client/src/utils/constants.tsx
Labels: feature, frontend

#103 env: Storybook setup #102
  client/.storybook/main.js
  client/.storybook/preview.js
  client/.storybook/webpack.config.js
  client/package.json
  client/src/components/atoms/Icon/Icon.stories.tsx
  client/src/components/atoms/Icon/Icon.tsx
  client/src/components/atoms/Logo/Logo.stories.tsx
  client/src/components/atoms/Logo/Logo.tsx
  client/src/components/modules/Header/Header.stories.tsx
  client/src/components/modules/Header/Header.tsx
  client/yarn.lock
Labels: env, feature, frontend

#99 Auth api#22
  server/src/controllers/auth-controller.ts
  server/src/controllers/cart-controller.ts
  server/src/controllers/category-controller.ts
  server/src/controllers/index.ts
  server/src/controllers/product-controller.ts
  server/src/controllers/sub-category-controller.ts
  server/src/models/cart-product.ts
  server/src/models/cart.ts
  server/src/models/category.ts
  server/src/models/index.ts
  server/src/models/login-provider.ts
  server/src/models/product.ts
  server/src/models/user.ts
  server/src/routers/auth-router.ts
  server/src/routers/cart-router.ts
  server/src/routers/index.ts
  server/src/routers/sub-category-router.ts
Labels: backend, feature

#104 feat: Toast modal 구현#46
  client/src/components/atoms/BottomBtn/BottomBtn.spec.tsx
  client/src/components/atoms/BottomBtn/BottomBtn.tsx
  client/src/components/atoms/BottomBtn/index.tsx
  client/src/components/atoms/BottomBtn/styled.tsx
  client/src/components/atoms/CounterBtn/CounterBtn.spec.tsx
  client/src/components/atoms/CounterBtn/CounterBtn.tsx
  client/src/components/atoms/CounterBtn/index.tsx
  client/src/components/atoms/CounterBtn/styled.tsx
  client/src/components/modules/ProductCard/ProductCard.tsx
  client/src/components/modules/ToastModal/ToastModal.spec.tsx
  client/src/components/modules/ToastModal/ToastModal.tsx
  client/src/components/modules/ToastModal/index.tsx
  client/src/components/modules/ToastModal/styled.tsx
  client/src/components/templates/SlidableContainer/SlidableContainer.tsx
  client/src/pages/index.tsx
  package.json
Labels: feature, frontend

#108 fix: 프론트 에러 수정#107
  client/package.json
  client/src/components/modules/ListLoading/ListLoading.tsx
  client/src/components/modules/ToastModal/ToastModal.tsx
  client/src/components/templates/SlidableContainer/SlidableContainer.tsx
  client/src/components/templates/TabViewContainer/TabViewContainer.tsx
  client/src/pages/index.tsx
Labels: bug, frontend

#110 feat: TabViewContainer API 연결 및 currentTab 표시 #106
  client/scripts/bulk_create_category.sh
  client/scripts/bulk_create_product.sh
  client/scripts/bulk_create_sub_category.sh
  client/src/components/templates/SlidableContainer/SlidableContainer.tsx
  client/src/components/templates/TabViewContainer/TabViewContainer.tsx
  client/src/components/templates/TabViewContainer/styled.tsx
  client/src/pages/index.tsx
  client/src/utils/constants.tsx
  server/src/controllers/product-controller.ts
  server/src/routers/product-router.ts
Labels: feature, frontend

#111 feat: ContextAPI 구현#109
  client/src/commons/Context/Context.tsx
  client/src/commons/Context/index.tsx
  client/src/commons/Layout/Layout.tsx
  client/src/commons/Layout/index.ts
  client/src/components/modules/ListLoading/ListLoading.tsx
  client/src/components/modules/ListLoading/index.tsx
  client/src/components/modules/ListLoading/styled.tsx
  client/src/components/modules/ProductCard/ProductCard.tsx
  client/src/components/modules/ToastModal/ToastModal.tsx
  client/src/components/templates/SlidableContainer/SlidableContainer.tsx
  client/src/components/templates/TabViewContainer/TabViewContainer.tsx
  client/src/pages/_app.tsx
  client/src/pages/about/index.tsx
  client/src/pages/index.tsx
  client/src/pages/temp/index.tsx
Labels: env, frontend

#112 feat: 미디어쿼리 이용 사이즈 조절#105
  client/src/commons/Layout/Layout.tsx
  client/src/commons/styles/Normalize.tsx
  client/src/components/atoms/CounterBtn/CounterBtn.tsx
  client/src/components/atoms/CounterBtn/styled.tsx
  client/src/components/modules/CategoryIcon/styled.tsx
  client/src/components/modules/Header/Header.tsx
  client/src/components/modules/Header/styled.tsx
  client/src/components/modules/ProductCard/styled.tsx
  client/src/components/modules/ToastModal/styled.tsx
  client/src/components/templates/CategoryContainer/CategoryContainer.tsx
  client/src/components/templates/CategoryContainer/styled.tsx
Labels: design, frontend

#113 feat: Banner 컴포넌트 기능 개선 #75
  client/.storybook/webpack.config.js
  client/public/assets/images/banners/big/banner-big-1.gif
  client/public/assets/images/banners/big/banner-big-2.gif
  client/public/assets/images/banners/big/banner-big-3.gif
  client/public/assets/images/banners/big/banner-big-4.gif
  client/public/assets/images/banners/big/banner-big-5.gif
  client/public/assets/images/banners/big/banner-big-6.gif
  client/public/assets/images/banners/big/banner-big-7.gif
  client/public/assets/images/banners/big/banner-big-8.gif
  client/public/assets/images/banners/big/banner-big-9.gif
  client/public/assets/images/banners/small/banner-small-1.jpg
  client/public/assets/images/banners/small/banner-small-2.jpg
  client/public/assets/images/banners/small/banner-small-3.jpg
  client/public/assets/images/banners/small/banner-small-4.jpg
  client/public/assets/images/banners/small/banner-small-5.jpg
  client/public/assets/images/categories/main-bread.png
  client/public/assets/images/categories/main-choco.png
  client/public/assets/images/categories/main-egg.png
  client/public/assets/images/categories/main-hair.png
  client/public/assets/images/categories/main-ice.png
  client/public/assets/images/categories/main-mealkit.png
  client/public/assets/images/categories/main-milk.png
  client/public/assets/images/categories/main-salad.png
  client/public/assets/images/categories/main-yasik.png
  client/public/assets/images/categories/more.png
  client/src/assets/images/coke.jpeg
  client/src/assets/images/index.tsx
  client/src/commons/Context/Context.tsx
  client/src/components/modules/Banner/Banner.tsx
  client/src/components/modules/Banner/index.tsx
  client/src/components/modules/Banner/styled.tsx
  client/src/components/modules/ProductCard/ProductCard.tsx
  client/src/components/templates/CategoryContainer/CategoryContainer.tsx
  client/src/components/templates/SlidableContainer/index.tsx
  client/src/pages/index.tsx
  client/src/utils/constants.tsx
  client/src/utils/customHooks.tsx
  client/src/utils/helper.tsx
  client/tsconfig.json
Labels: enhancement, feature, frontend

#114 Cart page#49
  client/next.config.js
  client/src/commons/Layout/Layout.tsx
  client/src/commons/Layout/index.ts
  client/src/components/atoms/BottomBtn/BottomBtn.tsx
  client/src/components/atoms/CounterBtn/CounterBtn.tsx
  client/src/components/atoms/CounterBtn/styled.tsx
  client/src/components/modules/CheckListHeader/CheckListHeader.tsx
  client/src/components/modules/CheckListHeader/index.tsx
  client/src/components/modules/CheckListHeader/styled.tsx
  client/src/components/modules/CheckableProduct/CheckableProduct.tsx
  client/src/components/modules/CheckableProduct/index.tsx
  client/src/components/modules/CheckableProduct/styled.tsx
  client/src/components/modules/Header/Header.tsx
  client/src/components/modules/Header/index.tsx
  client/src/components/modules/ToastModal/ToastModal.tsx
  client/src/components/templates/CheckListContainer/CheckListContainer.tsx
  client/src/components/templates/CheckListContainer/index.tsx
  client/src/components/templates/CheckListContainer/styled.tsx
  client/src/pages/_app.tsx
  client/src/pages/about/index.tsx
  client/src/pages/cart/index.tsx
  client/src/pages/index.tsx
  client/src/pages/temp/index.tsx
  client/src/utils/constants.tsx
Labels: bug, feature, frontend, style

#123 fix: Next 데이터 패치함수 수정
  client/src/pages/cart/index.tsx
  client/src/pages/index.tsx
Labels: feature, frontend

#124 fix: font 크기 수정 및 넘치는 글자 생략
  client/src/commons/styles/Normalize.tsx
  client/src/components/atoms/BottomBtn/styled.tsx
  client/src/components/modules/CheckListHeader/styled.tsx
  client/src/components/modules/CheckableProduct/CheckableProduct.tsx
  client/src/components/modules/CheckableProduct/styled.tsx
  client/src/components/modules/ContainerHeader/styled.tsx
  client/src/components/modules/Header/Header.tsx
  client/src/components/modules/Header/styled.tsx
  client/src/components/modules/ProductCard/ProductCard.tsx
  client/src/components/modules/ProductCard/styled.tsx
  client/src/components/modules/ToastModal/styled.tsx
Labels: design, frontend

#129 feat: 회원가입 페이지 구현#127
  client/src/commons/styles/Normalize.tsx
  client/src/components/atoms/Input/Input.spec.tsx
  client/src/components/atoms/Input/Input.tsx
  client/src/components/atoms/Input/index.tsx
  client/src/components/atoms/Input/styled.tsx
  client/src/components/templates/SignUpContainer/SignUpContainer.spec.tsx
  client/src/components/templates/SignUpContainer/SignUpContainer.tsx
  client/src/components/templates/SignUpContainer/index.tsx
  client/src/components/templates/SignUpContainer/styled.tsx
  client/src/pages/signup/index.tsx
Labels: feature, frontend

#138 Fix build error#137
  client/src/commons/Context/Context.tsx
  client/src/components/atoms/Icon/Icon.tsx
  client/src/components/atoms/Icon/styled.tsx
  client/src/components/modules/Header/Header.stories.tsx
  client/src/components/modules/Header/Header.tsx
  client/src/components/templates/CategoryContainer/CategoryContainer.tsx
  client/src/components/templates/CheckListContainer/CheckListContainer.tsx
  client/src/components/templates/OutOfStockContainer/OutOfStockContainer.tsx
  client/src/components/templates/SlidableContainer/SlidableContainer.tsx
  client/src/components/templates/TabViewContainer/TabViewContainer.tsx
Labels: bug, frontend

#142 chore: 유효성검사
  shared/validate.ts
Labels: feature

#143 feat: user name, email, password validation 추가 #140
  server/src/bulk-data/data/user.json
  server/src/bulk-data/index.ts
  server/src/controllers/auth-controller.ts
  server/src/models/login-provider.ts
  server/src/models/user.ts
  shared/validate.ts
Labels: backend, feature

#144 feat: 유효성 검사#130
  client/src/components/atoms/Input/Input.tsx
  client/src/components/atoms/Input/styled.tsx
  client/src/components/templates/SignInContainer/SignInContainer.tsx
  client/src/components/templates/SignUpContainer/SignUpContainer.tsx
  client/src/utils/validate.tsx
  client/tsconfig.json
Labels: feature, frontend

#147 Like#141
  client/src/commons/Context/Context.tsx
  client/src/components/modules/ProductCard/ProductCard.tsx
  client/src/components/templates/SignInContainer/SignInContainer.tsx
  client/src/components/templates/SlidableContainer/SlidableContainer.tsx
  client/src/pages/_document.tsx
  client/tsconfig.json
  server/src/bulk-data/data/products/fruits.json
  server/src/bulk-data/data/products/vegetables.json
  server/src/bulk-data/index.ts
  server/src/controllers/auth-controller.ts
  server/src/controllers/index.ts
  server/src/controllers/like-controller.ts
  server/src/models/index.ts
  server/src/models/like.ts
  server/src/models/user.ts
  server/src/modules/auth/passport.ts
  server/src/modules/exception/error-handler.ts
  server/src/routers/index.ts
  server/src/routers/like-router.ts
  tsconfig.json
Labels: backend, bug, frontend

#148 feat: page에 유저권한설정
  client/src/commons/Context/Context.tsx
  client/src/components/templates/SignInContainer/styled.tsx
  client/src/components/templates/SignUpContainer/styled.tsx
  client/src/pages/_app.tsx
  client/src/utils/cookie-manager.tsx
Labels: feature, frontend

#152 Link token api#149
  client/src/commons/Context/Context.tsx
  client/src/components/modules/ProductCard/ProductCard.tsx
  client/src/components/modules/ToastModal/ToastModal.tsx
  client/src/components/templates/SignInContainer/SignInContainer.tsx
  client/src/components/templates/SignUpContainer/SignUpContainer.tsx
  client/src/pages/_app.tsx
  client/src/utils/cookie-manager.tsx
  server/src/controllers/auth-controller.ts
  server/src/controllers/cart-controller.ts
  server/src/controllers/like-controller.ts
  server/src/routers/cart-router.ts
  server/src/routers/like-router.ts
Labels: backend, feature, frontend

#154 feat: 메뉴페이지#150
  client/package.json
  client/public/assets/images/categories/main-계란.png
  client/public/assets/images/categories/main-밀키트.png
  client/public/assets/images/categories/main-빵.png
  client/public/assets/images/categories/main-샐러드.png
  client/public/assets/images/categories/main-아이스크림.png
  client/public/assets/images/categories/main-야식.png
  client/public/assets/images/categories/main-우유.png
  client/public/assets/images/categories/main-초콜렛.png
  client/public/assets/images/categories/main-헤어.png
  client/src/components/atoms/Icon/Icon.tsx
  client/src/components/atoms/LinkBox/LinkBox.spec.tsx
  client/src/components/atoms/LinkBox/LinkBox.tsx
  client/src/components/atoms/LinkBox/index.tsx
  client/src/components/atoms/LinkBox/styled.tsx
  client/src/components/atoms/LogOut/LogOut.spec.tsx
  client/src/components/atoms/LogOut/LogOut.tsx
  client/src/components/atoms/LogOut/index.tsx
  client/src/components/atoms/LogOut/styled.tsx
  client/src/components/templates/CategoryNavContainer/CategoryNavContainer.spec.tsx
  client/src/components/templates/CategoryNavContainer/CategoryNavContainer.tsx
  client/src/components/templates/CategoryNavContainer/index.tsx
  client/src/components/templates/CategoryNavContainer/styled.tsx
  client/src/components/templates/MenuNavContainer/MenuNavContainer.spec.tsx
  client/src/components/templates/MenuNavContainer/MenuNavContainer.tsx
  client/src/components/templates/MenuNavContainer/index.tsx
  client/src/components/templates/MenuNavContainer/styled.tsx
  client/src/components/templates/SignInContainer/SignInContainer.tsx
  client/src/components/templates/SignInContainer/styled.tsx
  client/src/components/templates/SignUpContainer/SignUpContainer.tsx
  client/src/components/templates/SignUpContainer/styled.tsx
  client/src/pages/index.tsx
  client/src/pages/menu/index.tsx
  client/src/utils/constants.tsx
  client/yarn.lock
  server/scripts/bulk_create_category.sh
  server/src/bulk-data/data/category.json
Labels: feature, frontend

#156 feat: Category Page 구현 #151
  client/public/assets/images/categories/main-과일·샐러드.png
  client/public/assets/images/categories/main-과자·초콜릿.png
  client/public/assets/images/categories/main-분식·야식.png
  client/public/assets/images/categories/main-빵·시리얼·잼.png
  client/public/assets/images/categories/main-우유·유제품.png
  client/public/assets/images/categories/main-정육·수산·계란.png
  client/public/assets/images/categories/main-헤어·바디·세안.png
  client/src/components/atoms/SubButton/SubButton.tsx
  client/src/components/modules/Banner/Banner.tsx
  client/src/components/modules/CarouselBanner/CarouselBanner.tsx
  client/src/components/modules/ContainerHeader/ContainerHeader.tsx
  client/src/components/templates/CategoryContainer/CategoryContainer.tsx
  client/src/components/templates/ProductsByCategoryContainer/ProductsByCategoryContainer.tsx
  client/src/components/templates/ProductsByCategoryContainer/index.tsx
  client/src/components/templates/ProductsByCategoryContainer/styled.tsx
  client/src/components/templates/SlidableCategoryContainer/SlidableCategoryContainer.tsx
  client/src/components/templates/SlidableCategoryContainer/index.tsx
  client/src/components/templates/SlidableContainer/SlidableContainer.tsx
  client/src/components/templates/TabViewContainer/TabViewContainer.tsx
  client/src/pages/categories/[id].tsx
  client/src/pages/categories/styled.tsx
  client/src/pages/index.tsx
  client/src/utils/constants.tsx
  server/scripts/bulk_create_category.sh
  server/src/bulk-data/data/category.json
  server/src/controllers/category-controller.ts
  server/src/routers/category-router.ts
Labels: feature, frontend

#157 Fe token user#153
  client/.babelrc
  client/package.json
  client/src/components/modules/Header/Header.tsx
  client/src/components/modules/ProductCard/ProductCard.tsx
  client/src/components/templates/CategoryContainer/CategoryContainer.tsx
  client/src/components/templates/CheckListContainer/CheckListContainer.tsx
  client/src/components/templates/OutOfStockContainer/OutOfStockContainer.tsx
  client/src/components/templates/ProductsByCategoryContainer/ProductsByCategoryContainer.tsx
  client/src/components/templates/SlidableContainer/SlidableContainer.tsx
  client/src/components/templates/TabViewContainer/TabViewContainer.tsx
  client/src/pages/_app.tsx
  client/src/pages/cart/index.tsx
Labels: bug, env, frontend

#159 feat: footer 구현#158
  client/src/components/modules/Footer/Footer.tsx
  client/src/components/modules/Footer/styled.ts
  client/src/components/templates/SignInContainer/SignInContainer.tsx
  client/src/components/templates/SignUpContainer/SignUpContainer.tsx
  client/src/utils/constants.tsx
Labels: feature, frontend

#166 feat: 찜목록 페이지#160
  client/src/commons/styles/Normalize.tsx
  client/src/components/atoms/LogOut/LogOut.tsx
  client/src/components/atoms/LogOut/styled.tsx
  client/src/components/modules/Footer/styled.ts
  client/src/components/modules/ToastModal/styled.tsx
  client/src/components/templates/CategoryNavContainer/CategoryNavContainer.tsx
  client/src/components/templates/CategoryNavContainer/styled.tsx
  client/src/components/templates/FavoriteContainer/FavoriteContainer.spec.tsx
  client/src/components/templates/FavoriteContainer/FavoriteContainer.tsx
  client/src/components/templates/FavoriteContainer/index.tsx
  client/src/components/templates/FavoriteContainer/styled.tsx
  client/src/components/templates/MenuNavContainer/MenuNavContainer.tsx
  client/src/components/templates/MenuNavContainer/styled.tsx
  client/src/components/templates/SignInContainer/styled.tsx
  client/src/components/templates/SignUpContainer/styled.tsx
  client/src/pages/favorite/index.tsx
  client/src/pages/menu/index.tsx
Labels: feature, frontend

#168 chore: icon 타입지정#167
  client/src/components/atoms/Icon/Icon.tsx
  client/src/components/atoms/LogOut/LogOut.tsx
  client/src/components/atoms/SubButton/SubButton.tsx
  client/src/components/modules/Header/Header.tsx
  client/src/components/modules/ProductCard/ProductCard.tsx
  client/src/components/templates/MenuNavContainer/MenuNavContainer.tsx
  client/src/components/templates/OutOfStockContainer/OutOfStockContainer.tsx
  client/src/pages/cart/index.tsx
  client/src/pages/categories/[id].tsx
  client/src/pages/index.tsx
  client/src/pages/menu/index.tsx
  client/src/pages/signin.tsx
  client/src/pages/signup/index.tsx
  client/src/utils/constants.tsx
Labels: feature, frontend

#169 animate: item fade-in, item scale-in 적용 #162
  client/package.json
  client/src/animates/FadeIn/FadeIn.tsx
  client/src/animates/FadeIn/index.tsx
  client/src/animates/ScaleIn/ScaleIn.tsx
  client/src/animates/ScaleIn/index.tsx
  client/src/animates/ScaleIn/styled.tsx
  client/src/animates/index.tsx
  client/src/components/modules/ProductCard/ProductCard.tsx
  client/src/components/templates/CategoryContainer/CategoryContainer.tsx
  client/src/components/templates/CheckListContainer/CheckListContainer.tsx
  client/src/components/templates/OutOfStockContainer/OutOfStockContainer.tsx
  client/src/components/templates/ProductsByCategoryContainer/ProductsByCategoryContainer.tsx
  client/src/components/templates/SlidableContainer/SlidableContainer.tsx
  client/src/pages/index.tsx
  client/tsconfig.json
  client/yarn.lock
Labels: style

#170 Fetchable container#164
  client/src/components/atoms/Badge/styled.tsx
  client/src/components/atoms/LinkBox/LinkBox.tsx
  client/src/components/modules/ContainerHeader/styled.tsx
  client/src/components/modules/ProductCard/ProductCard.tsx
  client/src/components/modules/ProductCard/styled.tsx
  client/src/components/templates/CategoryContainer/CategoryContainer.tsx
  client/src/components/templates/CategoryContainer/styled.tsx
  client/src/components/templates/FavoriteContainer/FavoriteContainer.tsx
  client/src/components/templates/FetchableContainer/FetchableContainer.tsx
  client/src/components/templates/FetchableContainer/index.tsx
  client/src/components/templates/FetchableContainer/styled.tsx
  client/src/components/templates/ProductsByCategoryContainer/ProductsByCategoryContainer.tsx
  client/src/components/templates/ProductsByCategoryContainer/styled.tsx
  client/src/components/templates/SlidableContainer/styled.tsx
  client/src/components/templates/SubCategoryNavContainer/SubCategoryNavContainer.tsx
  client/src/components/templates/SubCategoryNavContainer/styled.tsx
  client/src/components/templates/TabViewContainer/styled.tsx
  client/src/pages/categories/[id].tsx
  client/src/pages/favorite/index.tsx
  client/src/pages/index.tsx
  client/src/pages/sub-categories/[id].tsx
Labels: feature, frontend

#172 feat: menu페이지에 하위카테고리
  client/src/components/templates/CategoryNavContainer/CategoryNavContainer.tsx
  client/src/components/templates/CategoryNavContainer/styled.tsx
  client/src/components/templates/SignUpContainer/styled.tsx
  client/src/pages/menu/index.tsx
Labels: feature, frontend

#175 Soldout imgmodal#174
  client/src/components/modules/OutOfStockProduct/styled.tsx
  client/src/components/modules/ProductCard/ProductCard.tsx
  client/src/components/modules/ProductCard/styled.tsx
  client/src/components/modules/TotalPriceInfo/styled.tsx
  client/src/components/templates/CheckListContainer/styled.tsx
  server/src/config/constants.ts
  server/src/controllers/auth-controller.ts
Labels: feature, frontend

#180 feat: 클릭 개수에 따른 동적 컨테이너 구현 #178
  client/src/commons/Context/Context.tsx
  client/src/components/modules/ProductCard/ProductCard.tsx
  client/src/components/templates/DynamicContainer/DynamicContainer.tsx
  client/src/components/templates/DynamicContainer/index.tsx
  client/src/components/templates/DynamicContainer/styled.tsx
  client/src/pages/index.tsx
Labels: feature, frontend

#181 feat: FetchableContainer 구현#177
  client/src/components/templates/DynamicContainer/DynamicContainer.tsx
  client/src/components/templates/FetchableContainer/FetchableContainer.tsx
  client/src/components/templates/TabViewContainer/TabViewContainer.tsx
  client/src/pages/categories/[id].tsx
  client/src/pages/index.tsx
  client/src/pages/sub-categories/[id].tsx
  client/src/utils/constants.tsx
  server/scripts/data/12-yogurt.txt
  server/scripts/data/13-butter.txt
  server/scripts/data/14-cheese.txt
  server/scripts/data/35-haagendaz-nature.txt
  server/scripts/data/36-stick-tube.txt
  server/src/bulk-data/data/products/12-yogurt.json
  server/src/bulk-data/data/products/13-butter.json
  server/src/bulk-data/data/products/14-cheese.json
  server/src/bulk-data/data/products/35-haagendaz-nature.json
  server/src/bulk-data/data/products/36-stick-tube.json
  server/src/bulk-data/data/products/45-now_need_necessary.json
  server/src/controllers/product-controller.ts
  server/src/routers/product-router.ts
Labels: feature, frontend

#185 feat: CartIcon 추가 #182
  client/src/components/modules/CartIcon/CartIcon.tsx
  client/src/components/modules/CartIcon/index.tsx
  client/src/components/modules/CartIcon/styled.tsx
  client/src/pages/categories/[id].tsx
  client/src/pages/favorite/index.tsx
  client/src/pages/index.tsx
  client/src/pages/sub-categories/[id].tsx
Labels: feature, frontend

#179 feat: 주문상세페이지#173
  client/public/assets/images/logo/bmart-logo.png
  client/src/components/atoms/BottomBtn/BottomBtn.spec.tsx
  client/src/components/atoms/CounterBtn/CounterBtn.spec.tsx
  client/src/components/atoms/GoogleLoginBtn/GoogleLoginBtn.spec.tsx
  client/src/components/atoms/Icon/Icon.spec.tsx
  client/src/components/atoms/Input/Input.spec.tsx
  client/src/components/atoms/LinkBox/LinkBox.spec.tsx
  client/src/components/atoms/LogOut/LogOut.spec.tsx
  client/src/components/atoms/Logo/Logo.spec.tsx
  client/src/components/modules/Header/Header.spec.tsx
  client/src/components/modules/HistoryCard/HistoryCard.tsx
  client/src/components/modules/HistoryCard/index.tsx
  client/src/components/modules/HistoryCard/styled.tsx
  client/src/components/modules/ProductDetailInfo/ProductDetailInfo.spec.tsx
  client/src/components/modules/ToastModal/ToastModal.spec.tsx
  client/src/components/templates/CategoryNavContainer/CategoryNavContainer.spec.tsx
  client/src/components/templates/CategoryNavContainer/CategoryNavContainer.tsx
  client/src/components/templates/FavoriteContainer/FavoriteContainer.spec.tsx
  client/src/components/templates/HistoryContainer/HistoryContainer.tsx
  client/src/components/templates/HistoryContainer/index.tsx
  client/src/components/templates/HistoryContainer/styled.tsx
  client/src/components/templates/MenuNavContainer/MenuNavContainer.spec.tsx
  client/src/components/templates/MenuNavContainer/MenuNavContainer.tsx
  client/src/components/templates/SignInContainer/SignInContainer.spec.tsx
  client/src/components/templates/SignUpContainer/SignUpContainer.spec.tsx
  client/src/pages/history/index.tsx
Labels: feature, frontend

#187 feat: 텅빈이미지 제작
  client/public/assets/images/tung/tung.png
  client/src/components/atoms/Tung/Tung.tsx
  client/src/components/atoms/Tung/index.tsx
  client/src/components/atoms/Tung/styled.tsx
  client/src/components/templates/CategoryNavContainer/CategoryNavContainer.tsx
  client/src/pages/categories/[id].tsx
  client/src/pages/sub-categories/[id].tsx
Labels: feature, frontend

#189 fix: 카테고리 선택시 폰트두께 수정
  client/src/components/templates/CategoryNavContainer/CategoryNavContainer.tsx
  client/src/components/templates/CategoryNavContainer/styled.tsx
Labels: design

#191 feat: HotDealPage 구현 및 카테고리 페이지 상품 분기
  client/src/components/templates/ProductsByCategoryContainer/ProductsByCategoryContainer.tsx
  client/src/components/templates/TabViewContainer/TabViewContainer.tsx
  client/src/pages/categories/[id].tsx
  client/src/pages/hotdeal/index.tsx
  client/src/pages/index.tsx
  client/src/utils/constants.tsx
Labels: feature, frontend
